import { escapeHtml as e } from "./templateEngine.js";

// Only trusted layout is raw. All customer values are escaped at the boundary.
export function luxuryBlocks(d, tpl) {
  const ru = d.lang === "ru";
  const image = e(tpl?.previewImage || "/app/assets/royal-palace.webp");
  const names = `${e(d.groom)} <i>&amp;</i> ${e(d.bride)}`;
  return {
    luxuryHead: `<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=Manrope:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/app/invitation.css"><meta name="theme-color" content="#191d17">`,
    luxuryEnvelope: `<div class="envx" id="envx"><div class="envelope-scene" aria-hidden="true"><img src="${image}" alt=""></div><div class="envelope-intro"><span class="small-label">${ru ? "ДЛЯ ВАС, С ЛЮБОВЬЮ" : "SIZ UCHUN, MEHR BILAN"}</span><p>${e(d.groom)} <i>&amp;</i> ${e(d.bride)}</p></div><div class="env" id="env" role="button" tabindex="0" aria-label="${e(d.L.openHint)}"><div class="env-back"></div><div class="env-paper"><span>${ru ? "ПРИГЛАШЕНИЕ НА СВАДЬБУ" : "TO‘Y TAKLIFNOMASI"}</span><p>${names}</p><small>${e(d.dateText)}</small></div><div class="env-front"></div><div class="env-flap"></div><div class="env-seal"><span>${e(d.groomInitial)}<i>&amp;</i>${e(d.brideInitial)}</span></div></div><p class="env-hint">${e(d.L.openHint)}</p><span class="envelope-brand">nvate</span></div>`,
    luxuryScene: `<div class="hero-scene" aria-hidden="true"><img src="${image}" alt="" fetchpriority="high"></div>`,
    luxuryLetter: `<section class="letter-section fx"><span class="section-number">01 — ${ru ? "ПРИГЛАШЕНИЕ" : "TAKLIFNOMA"}</span><h2>${d.guestName ? `${e(d.L.greet)}<br><em>${e(d.guestName)}</em>` : ru ? "Дорогие <em>и любимые</em>" : "Qadrli <em>yaqinlarimiz</em>"}</h2><span class="gold-rule" aria-hidden="true"></span><p>${e(d.L.invite)}</p><p class="letter-note">${e(d.L.emo)}</p><span class="signature">${names}</span></section>`,
    luxuryGallery: d.photos.length
      ? `<section class="photo-section fx" aria-label="${ru ? "Наши фотографии" : "Suratlarimiz"}"><div class="photo-layout">${d.photos.map((src, i) => `<figure class="couple-photo"><img src="${e(src)}" alt="${ru ? "Фотография пары" : "Juftlik surati"} ${i + 1}" loading="lazy" width="640" height="800"><figcaption>${String(i + 1).padStart(2, "0")} / ${ru ? "НАША ИСТОРИЯ" : "BIZNING HIKOYAMIZ"}</figcaption></figure>`).join("")}</div></section>`
      : "",
    luxuryDate: `<section class="date-section fx"><span class="section-number">02 — ${ru ? "НАШ ДЕНЬ" : "BIZNING KUN"}</span><h2>${ru ? "Сохраните <em>эту дату</em>" : "Bu sanani <em>eslab qoling</em>"}</h2><div class="date-plaque"><span>${e(d.monthName)}<br>${e(d.year)}</span><strong>${e(d.day)}</strong><span>${e(d.weekday)}<br>${e(d.time)}</span></div><button class="calendar-button" id="save-date" data-date="${e(d.dateIso)}" data-time="${e(d.time)}" data-groom="${e(d.groom)}" data-bride="${e(d.bride)}" data-address="${e(d.address)}">${ru ? "Добавить в календарь" : "Taqvimga qo‘shish"} <span>↗</span></button><p class="countdown-label">${e(d.L.until)}</p><div class="countdown" role="timer" aria-label="${e(d.L.until)}"><div><b id="cd">00</b><span>${e(d.L.days)}</span></div><i>:</i><div><b id="ch">00</b><span>${e(d.L.hours)}</span></div><i>:</i><div><b id="cm">00</b><span>${e(d.L.min)}</span></div><i>:</i><div><b id="cs">00</b><span>${e(d.L.sec)}</span></div></div></section>`,
    luxuryVenue: `<section class="venue-section fx"><span class="section-number">03 — ${ru ? "МЕСТО ВСТРЕЧИ" : "UCHRASHUV MANZILI"}</span><h2>${e(d.address)}</h2><p class="venue-time">${e(d.dateText)} · ${e(d.time)}</p>${d.mapEnabled ? d.map : ""}${d.mapEnabled ? `<div class="map-actions"><a href="${e(d.gmaps)}" target="_blank" rel="noopener">Google Maps ↗</a><a href="${e(d.ymaps)}" target="_blank" rel="noopener">Yandex Maps ↗</a></div>` : ""}</section>`,
    luxuryFooter: `<footer class="invitation-footer fx"><span class="small-label">${e(d.L.sign)}</span><p>${names}</p><span>${e(d.L.final)}</span><a href="/app/" class="invitation-brand" aria-label="${e(d.L.made)}">nvate</a></footer><script src="/app/invitation.js" defer></script>`,
  };
}
